# Generated by Django 6.0.4 on 2026-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('cover_image', models.URLField()),
                ('tags', models.JSONField(default=list)),
                ('published_at', models.DateField()),
                ('reading_time', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-published_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(default='work', max_length=50)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('github', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
